#' @useDynLib GEMSS, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

#' Correlation function of selected type, supporting both isotropic and product forms
#' @param X1 n by p matrix of input locations, one observation per row.
#' @param X2 matrix of design locations if correlation is calculated between \code{X1} and \code{X2} (otherwise calculated between \code{X1} and itself)
#' @param theta p by 1 vector of lengthscale parameters
#' @param type one of "\code{Gaussian}", "\code{Matern5_2}", "\code{Matern3_2}"
#' @export
#' @details
#' Definition of univariate correlation function and hyperparameters:
#' \itemize{
#' \item "\code{Gaussian}": \eqn{c(x, y) = exp(-(x-y)^2/theta)}
#' \item "\code{Matern5_2}": \eqn{c(x, y) = (1+sqrt(5)/theta * abs(x-y) + 5/(3*theta^2)(x-y)^2) * exp(-sqrt(5)*abs(x-y)/theta)}
#' \item "\code{Matern3_2}": \eqn{c(x, y) = (1+sqrt(3)/theta * abs(x-y)) * exp(-sqrt(3)*abs(x-y)/theta)}
#' }
#' Multivariate correlations are product of univariate ones.
compute_kernel <- function(X1, X2 = NULL, theta, type) {
  # Ensure inputs are matrices
  X1 <- as.matrix(X1)
  if(is.null(X2)){
    X2 <- as.matrix(X1)
  }
  return(compute_kernel_cpp(X1, X2, theta, type))
}


#' Gaussian Process Prediction
#'
#' @description
#' Performs Gaussian Process prediction for a given set of new design locations,
#' using hyperparameters provided in the Parameters list.
#'
#' @param X_new An \code{m x p} matrix of new design locations to predict.
#' @param X An \code{n x p} matrix of training design locations.
#' @param Y An \code{n x 1} vector of observed responses at training locations.
#' @param Cov_fun Covariance kernel type, either "Gaussian", "Matern5_2", or "Matern3_2".
#' @param Parameters A list of hyperparameters containing \code{theta}, \code{g}, \code{sigma2}, and \code{beta0}
#'
#' @return A list containing:
#' \itemize{
#'   \item \code{mean}: A vector of predicted means at \code{X_new}.
#'   \item \code{sd2}: A vector of predicted variances (posterior variances) at \code{X_new}.
#' }
#'
#' @details
#' The function uses the standard GP prediction formulas:
#' \deqn{\mu(x_{new}) = \beta_0 + k(x_{new}, X) K^{-1} (Y - \beta_0)}
#' \deqn{s^2(x_{new}) = \sigma^2 [ (1 + g) - k(x_{new}, X) (K + gI)^{-1} k(X, x_{new}) ]}
#'
#' @export
#' @export
gp_predict <- function(X_new, X, Y, Cov_fun, Parameters) {
  gp_predict_cpp(as.matrix(X_new), as.matrix(X), as.numeric(Y), Cov_fun, Parameters)
}


#' Generalization Error Minimization in SubSampling
#'
#' @description
#' Select subdata based on GEMSS criterion
#'
#' @param X An \code{n x p} matrix of input design locations.
#' @param Y An \code{n x 1} vector of observed responses.
#' @param ns Target size of the final subdata.
#' @param covtype Covariance kernel type, either "Gaussian", "Matern5_2", or "Matern3_2".
#' @param Parameters A list of hyperparameters: \code{beta0} (mean),
#' \code{theta} (length-scales), and \code{g} (nugget). If not provided,
#' these are estimated via \code{\link[hetGP]{mleHomGP}} on a pilot sample
#' generated by \code{\link[twinning]{twin}}.
#' @param X_val,Y_val Optional validation data for calculating the predictive R-squared.
#' If omitted, a random sample of size \code{min(0.1*n, 5000)} is used.
#' @param c1 Weight of the first term in GEMSS criterion (\eqn{c_2 = 1 - c_1}).
#' The default (\code{NULL}) uses the adaptive weighting proposed in the paper.
#' @param n_srs,n_top Optional values to determine the candidate set for each iteration:
#' \itemize{
#'   \item \code{n_srs}: Number of random data points (default is \code{ns/2}).
#'   \item \code{n_top}: Number of top-ranked points from the previous iteration (default is \code{ns/2}).
#' }
#' @param verbose Logical; if \code{TRUE}, progress is printed at each iteration.
#'
#' @return A list containing:
#' \itemize{
#'   \item \code{index}: The indices of the selected subdata.
#'   \item \code{r_sq}: A data.frame of size and predictive R-square.
#'   \item \code{sigma2}: Plug-in estimator of the variance.
#' }
#'
#' @details
#' The GEMSS criterion is \deqn{\tilde{\mathcal{G}} = c_1 \delta_1^2 + c_2 \delta_2}
#' where \eqn{\delta_1} is the prediction error and \eqn{\delta_2} is the posterior variance.
#' \eqn{c_1} and \eqn{c_2 = 1 - c_1} control the balance between prediction accuracy
#' and space-filling properties.
#'
#' @examples
#' # --- Example 1: 1D Regression ---
#' fx <- function(x) cos((x - 0.8) * 2 * pi)^7 * sin(x) + 5 * sin(x) * (sin(x^2))^10
#' X <- matrix(runif(200), 200, 1)
#' Y <- apply(X, 1, fx) + rnorm(nrow(X), 0, 0.05)
#'
#' # Select 20 points using GEMSS
#' res <- gemss_select(X, Y, ns = 20, covtype = "Matern5_2")
#'
#' # Predict on a grid
#' x.grid <- as.matrix(seq(0, 1, 0.01))
#' y.pred <- gp_predict(x.grid, X[res$index, ], Y[res$index], "Matern5_2", res$Parameters)
#'
#' # Visualize 1D Results
#' plot(X, Y, col = "gray", main = "GEMSS 1D Selection")
#' points(X[res$index, ], Y[res$index], col = "red", pch = 19)
#' lines(x.grid, y.pred$mean, col = "red", lwd = 2)
#'
#' # --- Example 2: 2D Surface (Michalewicz function) ---
#' \donttest{
#' michalewicz <- function(xx) {
#'   x1 <- xx[1] * pi; x2 <- xx[2] * pi; m <- 10
#'   - (sin(x1) * (sin(x1^2 / pi))^(2 * m) + sin(x2) * (sin(2 * x2^2 / pi))^(2 * m))
#' }
#'
#' X2D <- matrix(runif(2000), 1000, 2)
#' Y2D <- apply(X2D, 1, michalewicz) + rnorm(nrow(X2D), 0, 0.005)
#'
#' res2D <- gemss_select(X2D, Y2D, ns = 80, covtype = "Matern5_2")
#'
#' # Visualization using ContourFunctions if available
#' if (requireNamespace("ContourFunctions", quietly = TRUE)) {
#'   ngrid <- 50 # Reduced grid size for faster example execution
#'   gx <- seq(0, 1, len = ngrid)
#'   grid <- as.matrix(expand.grid(x1 = gx, x2 = gx))
#'   prep <- gp_predict(grid, X2D[res2D$index, ], Y2D[res2D$index], "Matern5_2", res2D$Parameters)
#'
#'   ContourFunctions::cf_grid(gx, gx, matrix(prep$mean, ngrid, ngrid),
#'                             bar = TRUE, main = "GEMSS 2D Selection",
#'                             afterplotfunc = function() {
#'                               points(X2D[res2D$index, ], col = 'blue', pch = 1, cex = 1.5, lwd = 2)
#'                             })
#' }
#' }
#'
#' @export
gemss_select <- function(X, Y, ns, covtype, Parameters = NULL, X_val = NULL, Y_val = NULL, c1 = NULL, n_srs = NULL, n_top = NULL, verbose = TRUE) {
  # 1. Validation
  if (nrow(X) != length(Y)) stop("Dimensions of X and Y do not match.")
  if (ns < 0 ) stop("ns should be positive integer")
  if (!(covtype %in% c("Gaussian", "Matern5_2", "Matern3_2"))) stop("covtype should be one of “Gaussian”, “Matern5_2”, “Matern3_2”")

  if (is.null(Parameters)) Parameters <- list()

  # 1. Validate theta length
  if (!is.null(Parameters$theta) && length(Parameters$theta) != ncol(X)) {
    warning("Length of theta does not match ncol(X). Estimating theta instead.")
    Parameters$theta <- NULL
  }

  # 2. Check for missingness (using || for safety)
  if (is.null(Parameters$theta) || is.null(Parameters$g) || is.null(Parameters$beta0)) {

    # Pilot Sample Selection
    ind_for_est <- twinning::twin(cbind(X, Y), r = floor(nrow(X) / ns))

    # Estimate only what is missing (known = Parameters handles the logic)
    est_GP <- hetGP::mleHomGP(
      X = X[ind_for_est, , drop = FALSE],
      Z = Y[ind_for_est],
      covtype = covtype,
      known = Parameters,
      maxit = 10000,
      noiseControl = list(g_bounds = c(sqrt(.Machine$double.eps), 10000))
    )

    # 3. Fill the gaps in Parameters list
    Parameters$theta <- est_GP$theta
    Parameters$g     <- est_GP$g
    Parameters$beta0 <- est_GP$beta0
  }

  # 3. Validation Set Handling
  if(is.null(X_val) || is.null(Y_val)){
    val_index <- sample(1:nrow(X), min(floor(0.1*nrow(X)), 5000))
    X_val <- X[val_index, , drop = FALSE]
    Y_val <- Y[val_index]

    not_val_ind <- setdiff(1:nrow(X), val_index)
    X <- X[not_val_ind, , drop = FALSE]
    Y <- Y[not_val_ind]
  }

  if(is.null(n_srs)) n_srs = ns/2
  if(is.null(n_top)) n_top = ns/2
  if(is.null(c1)){
    c1 = -1
  } else if (c1 > 1 || c1 < 0){
    stop("c1 is not between 0 and 1")
  }


  initial_idx <- sample(1:nrow(X), 2)

  # 3. Call C++
  results <- GEMSS_cpp_update_sig(
    X = as.matrix(X),
    Y = as.numeric(Y),
    X_val = as.matrix(X_val),
    Y_val = as.numeric(Y_val),
    initial_idx = initial_idx,
    ns = as.integer(ns),
    c1 = c1,
    n_srs = as.integer(n_srs),
    n_top = as.integer(n_top),
    theta = Parameters$theta,
    nugget = Parameters$g,
    beta0 = Parameters$beta0,
    Cov_fun = covtype,
    print_result = verbose
  )
  Parameters$sigma2 = results$sigma2
  # 4. Format Output
  list(
    index = not_val_ind[results$index],
    r_sq = results$r_sq,
    Parameters = Parameters
  )
}


