#' @useDynLib GEMSS, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

#' Compute the Correlation Matrix for Specified Kernels
#'
#' @description
#' Calculates the correlation matrix between two sets of locations using
#' stationary kernels. This function supports Gaussian, Matern 5/2, and
#' Matern 3/2 correlation structures in a multivariate product form.
#'
#' @param X1 an \code{n x p} matrix of input locations, where each row represents an observation.
#' @param X2 an \code{m x p} matrix of design locations. If \code{NULL}, the correlation
#' is calculated between \code{X1} and itself.
#' @param theta a \code{p x 1} vector of lengthscale parameters corresponding to each dimension.
#' @param type a character string specifying the kernel type: "\code{Gaussian}",
#' "\code{Matern5_2}", or "\code{Matern3_2}".
#'
#' @details
#' For multivariate inputs, the correlation function is defined as the product
#' of univariate kernels across all \eqn{p} dimensions:
#' \deqn{C(\mathbf{x}, \mathbf{y}, \boldsymbol{\theta}) = \prod_{k=1}^{p} c_k(|x_k - y_k|, \theta_k)}
#'
#' The available univariate correlation functions \eqn{c(d)} (where \eqn{d = |x - y|}) are:
#' \itemize{
#'   \item "\code{Gaussian}": \deqn{c(d, \theta) = \exp\left(-\frac{d^2}{\theta}\right)}
#'   \item "\code{Matern5_2}": \deqn{c(d, \theta) = \left(1 + \frac{\sqrt{5}d}{\theta} + \frac{5d^2}{3\theta^2}\right) \exp\left(-\frac{\sqrt{5}d}{\theta}\right)}
#'   \item "\code{Matern3_2}": \deqn{c(d, \theta) = \left(1 + \frac{\sqrt{3}d}{\theta}\right) \exp\left(-\frac{\sqrt{3}d}{\theta}\right)}
#' }
#'
#' @return A numeric matrix of dimensions \code{nrow(X1) x nrow(X2)}.
#' @export
compute_kernel <- function(X1, X2 = NULL, theta, type) {
  X1 <- as.matrix(X1)
  if(is.null(X2)){
    X2 <- as.matrix(X1)
  }
  return(compute_kernel_cpp(X1, X2, theta, type))
}


#' Gaussian Process Prediction
#'
#' @description
#' Performs Gaussian Process prediction for a given set of new design locations,
#' using hyperparameters provided in the parameters list.
#'
#' @param X_new an \code{m x p} matrix of new design locations to predict.
#' @param X an \code{n x p} matrix of training design locations.
#' @param Y an \code{n x 1} vector of observed responses at training locations.
#' @param Cov_fun covariance kernel type, either "Gaussian", "Matern5_2", or "Matern3_2".
#' @param parameters a list of hyperparameters containing \code{theta}, \code{g}, \code{sigma2}, and \code{beta0}
#'
#' @return a list containing:
#' \itemize{
#'   \item \code{mean}: a vector of predicted means at \code{X_new}.
#'   \item \code{sd2}: a vector of predicted variances (posterior variances) at \code{X_new}.
#' }
#'
#' @details
#' The function uses the standard GP prediction formulas:
#' \deqn{\mu(x_{new}) = \beta_0 + k(x_{new}, X) K^{-1} (Y - \beta_0)}
#' \deqn{s^2(x_{new}) = \sigma^2 [ (1 + g) - k(x_{new}, X) (K + gI)^{-1} k(X, x_{new}) ]}
#'
#' @export
gp_predict <- function(X_new, X, Y, Cov_fun, parameters) {
  gp_predict_cpp(as.matrix(X_new), as.matrix(X), as.numeric(Y), Cov_fun, parameters)
}


#' Generalization Error Minimization in SubSampling
#'
#' @description
#' Implements the Generalized Error-Minimizing Subsampling (GEMSS) algorithm to select subdata for
#' Gaussian Process models.
#'
#' @param X an \code{n x p} matrix of input design locations.
#' @param Y an \code{n x 1} vector of observed responses.
#' @param ns target size of the final subdata.
#' @param covtype covariance kernel type, either "Gaussian", "Matern5_2", or "Matern3_2".
#' @param parameters a list of hyperparameters: \code{beta0} (mean),
#' \code{theta} (length-scales), and \code{g} (nugget). If not provided,
#' these are estimated via \code{\link[hetGP]{mleHomGP}} on a pilot sample
#' generated by \code{\link[twinning]{twin}}.
#' @param X_val,Y_val optional validation data for calculating the predictive R-squared.
#' If omitted, a random sample of size \code{min(0.1*n, 5000)} is used.
#' @param c1 value between 0 and 1 of the first term in GEMSS criterion (\eqn{c_2 = 1 - c_1}).
#' The default (\code{NULL}) uses the adaptive weighting proposed in the paper.
#' @param n_srs,n_top optional values to determine the candidate set for each iteration:
#' \itemize{
#'   \item \code{n_srs}: number of random data points (default is \code{ns/2}).
#'   \item \code{n_top}: number of top-ranked points from the previous iteration (default is \code{ns/2}).
#' }
#' @param verbose logical; if \code{TRUE}, progress is printed at each iteration.
#'
#' @return A list containing:
#' \itemize{
#'   \item \code{index}: the indices of the selected subdata.
#'   \item \code{r_sq}: a data.frame containing the subdata size and the corresponding predictive R-square.
#'   \item \code{parameters}: a list of hyperparameters containing \code{beta0}, \code{theta}, \code{g}, and \code{sigma2} (the plug-in estimator of the variance).
#' }
#'
#' @details
#' The GEMSS criterion is defined as:
#' \deqn{\mathcal{G} = c_1 \delta_1^2 + c_2 \delta_2}
#' where \eqn{\delta_1^2} is the squared prediction error and \eqn{\delta_2} is the
#' posterior variance. The weights \eqn{c_1} and \eqn{c_2 = 1 - c_1} control the
#' balance between prediction accuracy and space-filling properties.
#'
#' The default value for \eqn{c_1} is \eqn{3\delta_2^2 / (2\delta_1^4 + 3\delta_2^2)},
#' which is derived by minimizing the variance of the GEMSS criterion. Setting
#' \eqn{c_1 = 0} results in a space-filling subdata
#'
#' The algorithm initializes with a small random sample of size 2 and
#' sequentially adds the point from the candidate set that maximizes \eqn{\mathcal{G}}
#' until the subdata reaches size ns.
#'
#' The candidate set in each iteration is composed of two parts: a random
#' sample of size n_srs, and the n_top points that yielded the highest
#' \eqn{\mathcal{G}} values in the previous iteration.
#'
#' All GP hyperparameters except \eqn{\sigma^2} are estimated from an initial
#' pilot sample of size \eqn{ns} and remain fixed throughout the selection process.
#'
#' @examples
#' # --- Example 1: 1D Regression ---
#' fx <- function(x) cos((x - 0.8) * 2 * pi)^7 * sin(x) + 5 * sin(x) * (sin(x^2))^10
#' X <- matrix(runif(200), 200, 1)
#' Y <- apply(X, 1, fx) + rnorm(nrow(X), 0, 0.05)
#'
#' # Select 20 points using GEMSS
#' res <- gemss_select(X, Y, ns = 20, covtype = "Matern5_2")
#'
#' # Predict on a grid
#' x.grid <- as.matrix(seq(0, 1, 0.01))
#' y.pred <- gp_predict(x.grid, X[res$index, ], Y[res$index], "Matern5_2", res$parameters)
#'
#' # Visualize 1D Results
#' plot(X, Y, col = "grey", main = "Selected Subdata and GP Prediction")
#' points(X[res$index, ], Y[res$index], col = "red", pch = 19)
#' lines(x.grid, y.pred$mean, col = "red", lwd = 2)
#'
#' # --- Example 2: 2D Surface (Michalewicz function) ---
#' \donttest{
#' michalewicz <- function(xx) {
#'   x1 <- xx[1] * pi; x2 <- xx[2] * pi; m <- 10
#'   - (sin(x1) * (sin(x1^2 / pi))^(2 * m) + sin(x2) * (sin(2 * x2^2 / pi))^(2 * m))
#' }
#'
#' X2D <- matrix(runif(2000), 1000, 2)
#' Y2D <- apply(X2D, 1, michalewicz) + rnorm(nrow(X2D), 0, 0.005)
#'
#' res2D <- gemss_select(X2D, Y2D, ns = 80, covtype = "Matern5_2")
#'
#' # Visualization using ContourFunctions if available
#' if (requireNamespace("ContourFunctions", quietly = TRUE)) {
#'   ngrid <- 50 # Reduced grid size for faster example execution
#'   gx <- seq(0, 1, len = ngrid)
#'   grid <- as.matrix(expand.grid(x1 = gx, x2 = gx))
#'
#'   # plot the contour of Michalewicz function
#'   y_grid <- apply(grid, 1, michalewicz)
#'   ContourFunctions::cf_grid(gx, gx, matrix(y_grid, ngrid, ngrid),
#'                           bar = TRUE, main = "Michalewicz Function")
#'
#'   prep <- gp_predict(grid, X2D[res2D$index, ], Y2D[res2D$index], "Matern5_2", res2D$parameters)
#'   ContourFunctions::cf_grid(gx, gx, matrix(prep$mean, ngrid, ngrid),
#'                             bar = TRUE, main = "Prediction Using Selected Subdata",
#'                             afterplotfunc = function() {
#'                               points(X2D[res2D$index, ], col = 'blue', pch = 1, cex = 1.5, lwd = 2)
#'                             })
#' }
#' }
#'
#' @export
gemss_select <- function(X, Y, ns, covtype, parameters = NULL, X_val = NULL, Y_val = NULL, c1 = NULL, n_srs = NULL, n_top = NULL, verbose = TRUE) {
  # 1. Validation
  if (nrow(X) != length(Y)) stop("Dimensions of X and Y do not match.")
  if (ns < 0 ) stop("ns should be positive integer")
  if (!(covtype %in% c("Gaussian", "Matern5_2", "Matern3_2"))) stop("covtype should be one of “Gaussian”, “Matern5_2”, “Matern3_2”")

  if (is.null(parameters)) parameters <- list()

  # 1. Validate theta length
  if (!is.null(parameters$theta) && length(parameters$theta) != ncol(X)) {
    warning("Length of theta does not match ncol(X). Estimating theta instead.")
    parameters$theta <- NULL
  }

  # 2. Check for missingness (using || for safety)
  if (is.null(parameters$theta) || is.null(parameters$g) || is.null(parameters$beta0)) {

    # Pilot Sample Selection
    ind_for_est <- twinning::twin(cbind(X, Y), r = floor(nrow(X) / ns))

    # Estimate only what is missing (known = parameters handles the logic)
    est_GP <- hetGP::mleHomGP(
      X = X[ind_for_est, , drop = FALSE],
      Z = Y[ind_for_est],
      covtype = covtype,
      known = parameters,
      maxit = 10000,
      noiseControl = list(g_bounds = c(sqrt(.Machine$double.eps), 10000))
    )

    # 3. Fill the gaps in parameters list
    parameters$theta <- est_GP$theta
    parameters$g     <- est_GP$g
    parameters$beta0 <- est_GP$beta0
  }

  # 3. Validation Set Handling
  if(is.null(X_val) || is.null(Y_val)){
    val_index <- sample(1:nrow(X), min(floor(0.1*nrow(X)), 5000))
    X_val <- X[val_index, , drop = FALSE]
    Y_val <- Y[val_index]

    not_val_ind <- setdiff(1:nrow(X), val_index)
    X <- X[not_val_ind, , drop = FALSE]
    Y <- Y[not_val_ind]
  }

  if(is.null(n_srs)) n_srs = ns/2
  if(is.null(n_top)) n_top = ns/2
  if(is.null(c1)){
    c1 = -1
  } else if (c1 > 1 || c1 < 0){
    stop("c1 is not between 0 and 1")
  }


  initial_idx <- sample(1:nrow(X), 2)

  # 3. Call C++
  results <- GEMSS_cpp_update_sig(
    X = as.matrix(X),
    Y = as.numeric(Y),
    X_val = as.matrix(X_val),
    Y_val = as.numeric(Y_val),
    initial_idx = initial_idx,
    ns = as.integer(ns),
    c1 = c1,
    n_srs = as.integer(n_srs),
    n_top = as.integer(n_top),
    theta = parameters$theta,
    nugget = parameters$g,
    beta0 = parameters$beta0,
    Cov_fun = covtype,
    print_result = verbose
  )
  parameters$sigma2 = results$sigma2
  # 4. Format Output
  list(
    index = not_val_ind[results$index],
    r_sq = data.frame(size = 3:ns, r_sq = round(results$r_sq[-c(1:2)], 4)),
    parameters = parameters
  )
}


