# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_kernel <- function(x1, x2, theta, type) {
    .Call(`_GEMSS_compute_kernel`, x1, x2, theta, type)
}

gp_predict_cpp <- function(X_new, X, Y, Cov_fun, Parameters) {
    .Call(`_GEMSS_gp_predict_cpp`, X_new, X, Y, Cov_fun, Parameters)
}

GEMSS_cpp_update_sig <- function(X, Y, X_val, Y_val, initial_idx, ns, c1, n_srs, n_top, theta, nugget, beta0, Cov_fun, print_result) {
    .Call(`_GEMSS_GEMSS_cpp_update_sig`, X, Y, X_val, Y_val, initial_idx, ns, c1, n_srs, n_top, theta, nugget, beta0, Cov_fun, print_result)
}

